Prevent race condition between SSHD#start and #setPort.
SEVERE: Failed SSHD.init
java.lang.Error: java.lang.reflect.InvocationTargetException
  at hudson.init.TaskMethodFinder.invoke(TaskMethodFinder.java:110)
  at hudson.init.TaskMethodFinder$TaskImpl.run(TaskMethodFinder.java:176)
  at org.jvnet.hudson.reactor.Reactor.runTask(Reactor.java:282)
  at jenkins.model.Jenkins$8.runTask(Jenkins.java:924)
  at org.jvnet.hudson.reactor.Reactor$2.run(Reactor.java:210)
  at org.jvnet.hudson.reactor.Reactor$Node.run(Reactor.java:117)
  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
  at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.reflect.InvocationTargetException
  at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
  at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  at java.lang.reflect.Method.invoke(Method.java:606)
  at hudson.init.TaskMethodFinder.invoke(TaskMethodFinder.java:106)
  ... 8 more
Caused by: java.lang.IllegalArgumentException: Bad port number: -1
  at org.apache.sshd.SshServer.checkConfig(SshServer.java:282)
  at org.apache.sshd.SshServer.start(SshServer.java:342)
  at org.jenkinsci.main.modules.sshd.SSHD.start(SSHD.java:109)
  at org.jenkinsci.main.modules.sshd.SSHD.init(SSHD.java:146)
  ... 13 more